CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categorie" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(7) NOT NULL
);

CREATE TABLE "level_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(12) NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" int NOT NULL
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(150) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(80) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) NOT NULL,
  "description" varchar(200) NOT NULL,
  "level_courses_id" int NOT NULL,
  "teachers_id" int NOT NULL,
  "categories_id" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses_id" int NOT NULL,
  "videos_id" int NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("id") REFERENCES "courses" ("teachers_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_courses_id") REFERENCES "level_courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("videos_id") REFERENCES "videos" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

INSERT INTO categories (categorie) VALUES ('programación'), ('inglés'), ('liderazgo');
INSERT INTO roles (role) VALUES ('admin'), ('teacher'), ('student');
INSERT INTO level_courses (level) VALUES ('begginer'), ('Intermediate'), ('Advanced');
INSERT INTO users (name, email, password, age, role_id) 
VALUES 
('Andrés Rodríguez', 'andresr@gmail.com', '123', 21, 1), 
('John Doe', 'jdoe@gmail.com', '753', 33, 3), 
('Will Smith', 'wsmith@gmail.com', '468', 44, 3), 
('Mariah Carey', 'mcarey@hotmail.com', '467', 53, 2), 
('Midu Dev', 'midud@yahoo.es', '321', 63, 2), 
('S4vitar Dev', 's4vitar@outlook.es', '478', 30, 2);
INSERT INTO teachers (users_id) VALUES (4), (5), (6);
INSERT INTO videos (title, url)
VALUES 
    ('Fundamentos de programacion', 'url1'), 
    ('Fundamentos de JavaScript', 'url2'), 
    ('Linux básico', 'url3'), 
    ('Fundamentos de Node.js', 'url4'),
    ('Fundamentos de Python', 'url5'), 
    ('Tiempos verbales en inglés', 'url6'), 
    ('Fundamentos de C#', 'url7'),
    ('Metodologías ágiles', 'url8');
INSERT INTO courses (title, description, level_courses_id, teachers_id, categories_id)
VALUES 
    ('Ciencia de datos', 'Lorem ipsum', 1, 3, 1),
    ('Front end web', 'Lorem ipsum', 1, 2, 1),
    ('Back end web', 'Lorem ipsum', 1, 2, 1),
    ('Cybersecurity', 'Lorem ipsum', 2, 3, 1),
    ('Scrum Master', 'Lorem ipsum', 2, 1, 3),
    ('Desarrollo de aplicaciones', 'Lorem ipsum', 3, 2, 1),
    ('Inglés', 'Lorem ipsum', 1, 1, 2);
INSERT INTO course_videos (courses_id, videos_id)
VALUES 
    (1, 1),
    (1, 5),
    (2, 2),
    (2, 1),
    (3, 1),
    (3, 2),
    (3, 4),
    (4, 5),
    (5, 8),
    (6, 7),
    (7, 6);

-- Visualizaciones de tablas
SELECT users.name, users.email, users.password, users.age, roles.role FROM users JOIN roles ON users.role_id=roles.id;
SELECT courses.title, courses.description, level_courses.level, users.name, categories.categorie FROM courses JOIN level_courses ON courses.le
vel_courses_id=level_courses.id JOIN teachers ON courses.teachers_id=teachers.id JOIN users ON teachers.users_id=users.id JOIN categories ON courses.categor
ies_id=categories.id;